import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
   <div>
     <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis neque placerat ac. </p>
      <br />
      <h2>All posts</h2>
    </div>
  )
}
